#!/bin/bash
#--------------------------------------------------------------
# This script runs 3dClustSim for each model using acf parameters 
# generated by calculate_group_average.R
#	
# D.Cos 2018.11.06
#--------------------------------------------------------------

# Set your study
STUDY=/projects/adapt_lab/shared/TPOT/TPOT_Scripts

# Set shell script to execute
SHELL_SCRIPT=3dClustSim.sh

# FP the results files
RESULTS_INFIX=3dclustsim

# Set output dir and make it if it doesn't exist
OUTPUTDIR=${STUDY}/fMRI/fx/thresholding/output/group

if [ ! -d ${OUTPUTDIR} ]; then
	mkdir -p ${OUTPUTDIR}
fi

# Set model dir and specify RX models
MODELDIR=/projects/adapt_lab/shared/TPOT/out/rx/models/affect/OneSample
MODELS=(Label_Blur Label_View LabelAngry_Blur LabelAngry_IB LabelAngry_LabelSad LabelAngry_ViewAngry LabelHappy_Blur LabelHappy_IB LabelHappy_LabelAngry LabelHappy_ViewHappy LabelSad_Blur LabelSad_IB LabelSad_LabelHappy LabelSad_ViewSad View_Blur ViewAngry_Blur ViewAngry_IB ViewAngry_ViewSad ViewHappy_Blur ViewHappy_IB ViewHappy_ViewAngry ViewSad_Blur ViewSad_IB ViewSad_ViewHappy)

# Set job parameters
cpuspertask=1
mempercpu=8G

# Create and execute batch job
for MODEL in ${MODELS[@]}; do
 	sbatch -A adapt_lab \
 		--export=ALL,MODEL=$MODEL,MODELDIR=$MODELDIR,OUTPUTDIR=$OUTPUTDIR \
	 	--job-name=${RESULTS_INFIX} \
	 	-o ${OUTPUTDIR}/${MODEL}_${RESULTS_INFIX}.log \
	 	--cpus-per-task=${cpuspertask} \
	 	--mem-per-cpu=${mempercpu} \
	 	--account=adapt_lab \
	 	${SHELL_SCRIPT}
 	sleep .25
done
