#!/bin/bash
#--------------------------------------------------------------
# This script runs 3dClustSim for each model using acf parameters 
# generated by calculate_group_average.R
#	
# D.Cos 2018.11.06
#--------------------------------------------------------------

# Set your study
STUDY=/projects/adapt_lab/shared/TPOT/TPOT_Scripts

# Set shell script to execute
SHELL_SCRIPT=3dClustSim.sh

# FP the results files
RESULTS_INFIX=3dclustsim

# Set output dir and make it if it doesn't exist
OUTPUTDIR=${STUDY}/fMRI/thresholding/output/groupgroup

if [ ! -d ${OUTPUTDIR} ]; then
	mkdir -p ${OUTPUTDIR}
fi

# Set model dir and specify RX models
MODELDIR=/projects/adapt_lab/shared/TPOT/out/rx/models/affect/TwoSample
MODELS=(group_label_blur group_label_view group_labelangry_blur group_labelangry_IB group_labelangry_labelsad group_labelangry_viewangry group_labelhappy_blur group_labelhappy_IB group_labelhappy_labelangry group_labelhappy_viewhappy group_labelsad_blur group_labelsad_IB group_labelsad_labelhappy group_labelsad_viewsad group_view_blur group_viewangry_blur group_viewangry_IB group_viewangry_viewsad group_viewhappy_blur group_viewhappy_IB group_viewhappy_viewangry group_viewsad_blur group_viewsad_IB group_viewsad_viewhappy)

# Set job parameters
cpuspertask=1
mempercpu=8G

# Create and execute batch job
for MODEL in ${MODELS[@]}; do
 	sbatch -A adapt_lab \
 		--export=ALL,MODEL=$MODEL,MODELDIR=$MODELDIR,OUTPUTDIR=$OUTPUTDIR \
	 	--job-name=${RESULTS_INFIX} \
	 	-o ${OUTPUTDIR}/${MODEL}_${RESULTS_INFIX}.log \
	 	--cpus-per-task=${cpuspertask} \
	 	--mem-per-cpu=${mempercpu} \
	 	--account=adapt_lab \
	 	${SHELL_SCRIPT}
 	sleep .25
done
